[package]
	edition = "2021"
	name = "tmp_issue_repro_diesel_3522"
	version = "0.1.0"

[dependencies]
	diesel = { git = "https://github.com/diesel-rs/diesel", rev = "f39703734dac9a299f0c6c14f8d192c164b7b860" }
